### ISSUE TITLE
[Epic#22] 채널세팅에서 채널 내 수용인원을 설정할 수 있다

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#121]
# [Epic#22] 채널세팅에서 채널 내 수용인원을 설정할 수 있다

- Manday: 1.5

## 완료 조건 ✅

- [ ] 참여인원이 몇명인지 확인할 수 있다. 이슈 완성하기.
- [ ] 채널세팅에서 사용할 UI만들기.
- [ ] 참여인원이 몇명인지 확인 해, 넘으면 입장 불가 하도록 설정.
- [ ] 입장이 불가 할 때 적절한 에러 메시지 및 팝업 구현.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by devjaewon** [comment]
다음 버전으로 이관하여 이슈 닫겠습니다.
