### ISSUE TITLE
[Epic#2, Epic#23] 채널 만료기간을 수정할 수 있다

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#125]
# [Epic#2, Epic#23] 채널 만료기간을 수정할 수 있다

- 채널이 만료되면 해당 채날에 더이상 입장할 수 없어야한다.
- 이는 우리의 수익모델 중 하나가 될 기능이다.

## 완료 조건 ✅

- [ ] 채널설정 모달 UI가 필요하다.
- [ ] 모달 UI에서 만료기간을 설정할 수 있다.
- [ ] 만료된 채널에는 더이상 입장할 수 없다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by devjaewon** [comment]
추후 상품화 단계에서 기획하고 우선은 기획에서 제외한다.
