### ISSUE TITLE
[Epic#21] 스피커는 채널 설정에서 익명 채팅을 활성화 할수 있음

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#131]
# [Epic#21] 스피커는 채널 설정에서 익명 채팅을 활성화 할수 있음

## 완료 조건 ✅

- [x] 스피커가 채널 설정버튼을 누르면 모달창이 뜬다.
- [x] 모달창에서 토글 버튼으로 익명채팅을 활성화할 있다.
- [x] 디폴트로 익명채팅이 활성화되어있다.
- [x] 익명채팅을 비활성화하면 익명 사용자는 채팅이 불가하다.
- [x] 익명사용자가 채팅을 시도하면 placeholder 등에 로그인해주세요 라는 가이드가 표시된다.

## 관련 이슈 📎

- 이슈명 (#이슈번호)

## 레퍼런스 📚

> 레퍼런스 없음
