### ISSUE TITLE
[Epic#24, Epic#26] Canvas가 resize될 때, 이전의 Canvas content를 유지할 수 있어야 한다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#144]
# [Epic#24, Epic#26] Canvas가 resize될 때, 이전의 Canvas content를 유지할 수 있어야 한다.

- Canvas는 resize될 때, 이전의 Canvas content를 유지하지 않는다.
- 하지만, Canvas가 resize될 때에도 이전에 스피커가 필기한 내용이 사라지면 안되기 때문에, 이전의 Canvas content를 유지하는 방법을 고안해야 한다.

## 완료 조건 ✅
- [x] Canvas 모듈화
- [x] Canvas 위에 그림을 그릴 때, 발생하는 이벤트의 좌표값을 가로/세로 비율에 맞게 계속해서 저장한다.
- [x] Canvas가 resize 될 때, 기존에 저장해 두었던 좌표값 히스토리 순서에 맞게 새로운 Canvas에 그려준다.
- [ ] Canvas가 resize 될 때, 지속적으로 발생했던 렌더링을 최적화한다.

## 관련 이슈 📎
- [Epic#24, Epic#26] (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다. (#86)

## 레퍼런스 📚
- [Throttle, Debounce](https://webclub.tistory.com/607)
