### ISSUE TITLE
[Epic#38] 이모지를 채널에 날릴 수 있다!🤭v2

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#159]
# [Epic#38] 이모지를 채널에 날릴 수 있다!🤭

- 기존에 작업한 날아가는 이모지에 문제가 있다.
1. 최초 이벤트 발생자의 좌표를 가지고 가니 모니터 크기별 틀리게 보인다.
2. 많은 양의 작업이 onblur 일 때, 쌓였다가 한번에 방출된다.

## 완료 조건 ✅

- [x] 이모지의 출발점이 해당 버튼에서 시작되야 한다.
- [x] 이모지의 크기와 비율이 적절하다.
- [x] 날아가는 이모지가 onblur일 때, 쌓이지 않도록 설정한다.

## 관련 이슈 📎

- [Epic#38] 이모지를 채널에 날릴 수 있다!🤭(#87)

## 레퍼런스 📚

> 레퍼런스 없음
