### ISSUE TITLE
[Epic#11] 업로드 한 슬라이드를 이미지 형태로 볼 수 있다.

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#23]
# [Epic#11] 업로드 한 슬라이드를 이미지 형태로 볼 수 있다.

- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 1.5

  <br>

## 완료 조건 ✅

- [x] 슬라이드(pdf,ppt) 업로드가 가능하다.
- [x] 업로드된 슬라이드는 서버에서 이미지로 파싱된다.
- [x] 슬라이드 이미지는 구조화되어 서버에 저장된다.

  <br>

## 관련 이슈 📎

- [Epic#12] 파일 업로드 시 새로운 채널이 생성된다. (#25 )

  <br>

## 레퍼런스 📚

- [제품백로그](https://docs.google.com/spreadsheets/d/1YE7uJFBmL3xCaZYRoaxV8CroAN2vEo2TEbEWLn7zh2g/edit#gid=0)
- [화면기획서](https://docs.google.com/presentation/d/14fJYKn49Dqipuvr0yJMEFKmG6PMuUL5e1-3ZkHKOMb0/edit)
- [imagemagick npm](https://www.npmjs.com/package/imagemagick)
- [pdf-image npm](https://www.npmjs.com/package/pdf-image)
- [ppt-png npm](https://www.npmjs.com/package/ppt-png)

  <br>
