### ISSUE TITLE
[Epic#15, Epic#41] 채널에 입장하여 채팅할 수 있다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#24]
# [Epic#15, Epic#41] 채널에 입장하여 채팅할 수 있다

- 스피커와 리스너가 사용할 수 있는 채팅을 구현한다.

## 완료 조건 ✅

- [x] 사용자가 채널에 입장할 수 있다.
- [x] 사용자가 채팅을 입력할 수 있다.
- [x] 채팅 UI에 입력 버튼이 있다.
- [x] 입력한 채팅이 있는 상태에서 입력 버튼을 누르면, 채팅이 화면에 나타난다.
- [x] 화면에 나타난 채팅이 상태에 따라 위치가 변동 된다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

- [제품백로그](https://docs.google.com/spreadsheets/d/1YE7uJFBmL3xCaZYRoaxV8CroAN2vEo2TEbEWLn7zh2g/edit)
- [화면기획서](https://docs.google.com/presentation/d/14fJYKn49Dqipuvr0yJMEFKmG6PMuUL5e1-3ZkHKOMb0/edit#slide=id.g6addb83f12_0_30)
