### ISSUE TITLE
[Epic#12] 파일 업로드 시 새로운 채널이 생성된다.

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#25]
# [Epic#12] 파일 업로드 시 새로운 채널이 생성된다.

- 메인 화면에서 채널생성하기 버튼 클릭시 파일을 업로드하는 딤이 노출된다.
- 업로드 버튼을 통해 업로드시 채널이 생성된다.
- 또는 드래그앤드롭을 통해 채널 생성도 가능하다.

## 완료 조건 ✅

- [x] 파일 업로드 버튼 UI를 구현한다.
- [x] 파일 업로드 시 채널 코드가 생성된다.(util로 구현)
- [x] 파일 업로드 시 새로운 url의 채널 창이 켜진다.
- [x] 채널 데이터가 디비에 저장된다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
