### ISSUE TITLE
[Epic#18, Epic#43] 특정 채팅글에 좋아요 가능하다.

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#40]
# [Epic#18, Epic#43] 특정 채팅글에 좋아요 가능하다.

- 채팅에 좋아요가 가능해야 한다.
- 좋아요는 한번만 가능해야 한다.

## 완료 조건 ✅

- [x] 익명의 사용자에게도 익명 사용자 토큰을 넘겨주도록 인증시스템을 수정한다.
- [x] 좋아요을 하기 위해서 채팅 UI를 완성한다.
- [x] DB에 좋아요 로그를 저장한다.
- [x] 좋아요를 한 채팅은 다시 좋아요 하지 못하도록 한다.
- [x] 좋아요 상태를 채팅 UI에 표시한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
