### ISSUE TITLE
[Epic#3] 로그인 된 사용자는 마이페이지로 이동 할 수 있다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#41]
# [Epic#3] 로그인 된 사용자는 마이페이지로 이동 할 수 있다.

- 마이페이지 UI 생성해야 한다.
- 회원 정보를 다뤄야 한다.
- 데이터베이스 스키마 정의를 해야 한다.

## 완료 조건 ✅

- [x] 새로운 페이지를 만들어야 한다.
- [x] 프로젝트의 컬러에 맞는 UI를 그려야 한다.
- [x] 기존의 구조에 맞게 컴포넌트를 설계해야 한다.
- [x] 로그인 된 사용자만 사용하며, 상태를 확인해야 한다.
- [x] 회원정보를 담은 스키마를 정의해야 한다.
- [x] 채널정보를 담은 스키마를 정의해야 한다.
- [x] 히스토리를 담은 스키마를 정의해야 한다.

## 관련 이슈 📎

> 관련 이슈 없음

- 이슈명 (#이슈번호)

## 레퍼런스 📚

> 레퍼런스 없음
