### ISSUE TITLE
[Epic#14, Epic#35] 슬라이드를 앞뒤로 넘길 수 있다.

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#42]
# [Epic#14, Epic#35] 슬라이드를 앞뒤로 넘길 수 있다.

- 채널입장 시 슬라이드 뷰어가 생성된다.
- 슬라이더 뷰어의 `indicator`를 통해 슬라이드를 앞뒤로 넘긴다.
- 첫페이지와 마지막페이지에서는 각각 왼쪽, 오른쪽 indicator가 비활성화 된다.

## 완료 조건 ✅
- [x] 슬라이드 뷰어 UI 구현 
- [x] 슬라이드 back, foward 페이지 이동 구현
- [x] 이미지 로딩 로직 구현

## 관련 이슈 📎

-  스피커의 화면을 동기화하여 볼 수 있다.(#47)

## 레퍼런스 📚
- [화면기획서](https://www.figma.com/file/C6WPiScnuYSD9NI6gpPV0F/UI?node-id=0%3A1)
