### ISSUE TITLE
[Epic#8, Epic#10] 스피커, 리스너의 히스토리카드로 채널 입장 가능

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#44]
# [Epic#8, Epic#10] 스피커, 리스너의 히스토리카드로 채널 입장 가능

- 채널 정보를 다뤄야 한다.
- 회원 정보를 다뤄야 한다.
- 데이터베이스 스키마 정의를 해야 한다.

## 완료 조건 ✅

- [x] 스피커와 리스너를 구별해야 한다.
- [x] GraphQL을 이용해 최소한의 정보를 불러와야 한다.
- [x] 히스토리카드 UI 컴포넌트를 생성해야 한다.
- [x] 서버와 연동해야한다.

## 관련 이슈 📎

- [Epic#3] 로그인 된 사용자는 마이페이지로 이동할 수 있다. (#41)

## 레퍼런스 📚

> 레퍼런스 없음
