### ISSUE TITLE
[Epic#32] 스피커의 화면을 동기화하여 볼 수 있다.

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#47]
# [Epic#32] 스피커의 화면을 동기화하여 볼 수 있다.

- 스피커의 현재 슬라이드 페이지를 리스너가 구독하도록 한다.

## 완료 조건 ✅

- [x] 슬라이드 동기화 버튼 UI구현
- [x] 스피커의 현재 위치를 DB에 저장한다.
- [x] 리스너가 채널 접속시 스피커의 현재위치를 동기화 하여 보여준다.
- [x] 클라이언트에서 스피커의 위치를 리스너가 subscribe해야한다.
- [x] 동기화 활성화 시 리스너와 스피커의 슬라이드가 동기화 된다.

## 관련 이슈 📎

- 슬라이드를 앞뒤로 넘길 수 있다. (#42)

## 레퍼런스 📚

- [화면기획서](https://www.figma.com/file/C6WPiScnuYSD9NI6gpPV0F/UI?node-id=0%3A1)
