### ISSUE TITLE
[Epic#11]  메인 화면에서 슬라이드를 드롭다운 할 수 있다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#48]
# [Epic#11]  메인 화면에서 슬라이드를 드롭다운 할 수 있다.

- 메인화면에서 파일을 드롭다운 할 수 있어야 한다. 

## 완료 조건 ✅
- [x] 메인 화면의 Drag & Drop Page에 파일을 드롭다운 할 수 있다.
- [x] 파일을 드롭다운하면, 파일이 `image-converter` 서버로 전송된다. 
- [x] `image-converter` 서버의 응답이 있기 전까지는 유저에게 `로딩화면`을 보여준다.
- [x] `image-converter` 서버의 응답이 `ok`라면, 채널 화면이 보여지도록 한다.
- [x] `image-converter` 서버의 응답이 `ok`가 아니라면(error 발생), `에러 페이지`를 보여준다.

## 관련 이슈 📎
- [Epic#31] 채널 코드를 입력할 수 있다. (#50)
- [Epic#13, Epic#37] 공유 버튼을 이용해서 생성한 프레젠테이션 채널 코드를 복사하고, 공유할 수 있다. (#51)

## 레퍼런스 📚
> 레퍼런스 없음
