### ISSUE TITLE
[Epic#31] 채널 코드를 입력할 수 있다. 

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#50]
# [Epic#31] 채널 코드를 입력할 수 있다. 

- 채널 코드를 입력하면, 해당 채널 코드를 갖고 있는 채널 페이지로 이동할 수 있다.
- 입력한 채널 코드와 같은 채널 코드를 갖고 있는 채널이 있다면, 채널 목록 페이지로 이동한다.

## 완료 조건 ✅
- [x] 채널 코드를 입력할 수 있는 `Input 컴포넌트`를 생성해야 한다.
- [x] 만약, 입력한 채널의 코드가 다른 채널의 코드와 동일하다면, 동일한 채널 코드를 갖는 채널 목록을 보여주는 페이지가 보여진다. (채널 목록은 스크롤 되어야 한다.)
- [x] 채널 목록 페이지에는 `헤더`와 채널 정보가 담겨있는 `채널 카드 컴포넌트` 리스트가 보여진다.
- [x] 특정 카드를 클릭하면 해당 채널 페이지가 보여진다.
- [x] 선택된 채널 페이지로 이동할 때, 채널 컴포넌트가 로딩되기 전까지는 `로딩화면`이 보여진다.
- [x] 같은 채널 코드를 갖고 있는 채널이 없다면, 바로 채널 화면이 보여진다.

## 관련 이슈 📎

- [Epic#11] 메인 화면에서 슬라이드를 드롭다운 할 수 있다. (#48)
- [Epic#13, Epic#37] 공유 버튼을 이용해서 생성한 프레젠테이션 채널 코드를 복사하고, 공유할 수 있다. (#51)

## 레퍼런스 📚

> 레퍼런스 없음
