### ISSUE TITLE
[Epic#15, Epic#41] 채팅 기능 보완

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#55]
# [Epic#15, Epic#41] 채팅 기능 보완

- 2주차 스프린트 때 완료한 채팅기능이 미흡한 부분이 있어서 보완해야한다.
- 채팅이 쭉 쌓일 때, 스크롤바의 상태가 가장 최근 채팅을 볼 수 있도록 맞춰져야 한다.
- 처음 화면 진입시 기존의 채팅들을 불러와야 한다.
- 채팅을 하면 인풋창이 초기화 되어야 한다.
- 채팅창에서 엔터키를 이용해도 전송이 가능하다.

## 완료 조건 ✅

- [x] 채팅 전송시 Input 창 클리어
- [x] 채팅 Input에서 엔터키를 이용해서 전송이 가느해야한다.
- [x] 화면 진입시 기존의 채팅로그를 모두 불러온다.
- [x] 채팅이 올라오면 가장 최근의 채팅이 보여야한다.

## 관련 이슈 📎

- [Epic#15, Epic#41] 채널에 입장하여 채팅할 수 있다 (#24)

## 레퍼런스 📚

> 레퍼런스 없음
