### ISSUE TITLE
[Epic#15, Epic#41] 채팅 스타일 및 애니메이션 적용

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#62]
# [Epic#15, Epic#41] 채팅 스타일 및 애니메이션 적용

- 좋아요 버튼 클릭시 애니메이션이 적용된다.

## 완료 조건 ✅

- [x] 채팅창 너비 변경
- [x] 채팅에 좋아요를 누를 때 천천히 변화하는 애니메이션 적용
- [x] 채팅 정렬시 스크롤 변경 알고리즘 수정

## 관련 이슈 📎

- [Epic#15, Epic#41] 채팅 기능 보완 (#55)
- [Epic#15, Epic#41] 채널에 입장하여 채팅할 수 있다 (#24)

## 레퍼런스 📚

> 레퍼런스 없음
