### ISSUE TITLE
[Epic#14, Epic#35] 슬라이드 UI 보완

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#66]
# [Epic#14, Epic#35] 슬라이드 UI 보완
- MVP로 구현했던 슬라이드 뷰어 컴포넌트를 디테일하게 구현해야 합니다.
- 슬라이드가 겹처지는 부분과 애니메이션을 구현할 예정입니다.

## 완료 조건 ✅

- [x] 슬라이드의 남은 페이지를 표시하는 겹쳐진 페이지 UI를 구현한다.
- [x] 슬라이드 비율에 따라 렌더링 되어야 한다.
- [ ]  첫장과 마지막장에는 각각 왼쪽, 오른쪽에 겹쳐진 페이지가 보이지 않도록 구현한다.
- [ ] 두번째장과 뒤에서 두번째장에서는 겹쳐진 페이지가 한장만 보이도록 구현한다.

## 관련 이슈 📎
- 슬라이드를 앞뒤로 넘길 수 있다. (#42)

## 레퍼런스 📚

- [화면기획서](https://www.figma.com/file/C6WPiScnuYSD9NI6gpPV0F/UI?node-id=49%3A135)

**Comment by devjaewon** [comment]
기획 중간변경으로 이슈 닫겠습니다.
