### ISSUE TITLE
[Epic#29, Epic#36] 자료 다운로드 버튼을 활성화할 수 있다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#82]
# [Epic#29, Epic#36] 자료 다운로드 버튼을 활성화할 수 있다.
- 채널에 공유된 자료를 다운받을 수 있어야 한다.

## 완료 조건 ✅

- [x] 다운로드 버튼이 필요하다.
- [x] 기존 UI에 맞춰 버튼을 생성한다.
- [x] Object Storage에 있는 URL을 불러올 수 있다.
- [x] 다운로드가 정상적으로 작동한다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
