### ISSUE TITLE
[Epic#27, Epic#34] 채널의 슬라이드를 전체화면으로 볼 수 있다.

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#85]
# [Epic#27, Epic#34] 채널의 슬라이드를 전체화면으로 볼 수 있다.

- 채널의 슬라이드를 전체화면으로 볼 수 있어야 한다.
- 가능하다면, 이벤트 동작도 처리할 수 있게 만들어야 한다.
- ManDay : 1

## 완료 조건 ✅

- [x] 채널에 있는 슬라이드를 전체화면으로 전환시킬 수 있다.
- [x] 전체화면일 때, 동기화가 이루어 져야 한다. ( 리스너 )
- [x] 가능하다면, 전체화면에서 특정 작업을 진행할 수 있다.( 이벤트 )

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음
