### ISSUE TITLE
[Epic#24, Epic#26] (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#86]
# (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다.

- 스피커는 슬라이드에 필기도구를 이용해 필기를 기입할 수 있다.

## 완료 조건 ✅
- [x] 채널 화면 좌측의 필기 버튼 UI 구현
- [ ] '볼펜' 필기 도구 버튼이 활성화되면, **슬라이드 내**에서만 필기도구로 필기를 할 수 있어야 한다.
- [ ] '지우개' 필기 도구 버튼이 활성화되면, **슬라이드 내** 필기를 지울 수 있어야 한다.
- [ ] '형광펜' 필기 도구 버튼이 활성화되면, **슬라이드 내**에서만 필기 도구로 필기를 할 수 있어야 한다. (역시 지우개로 지울 수 있다.)

## 관련 이슈 📎
- 필기 가리기 버튼을 클릭하면, 스피커의 필기 내용이 삭제된다. (#88)

## 레퍼런스 📚

> 레퍼런스 없음
