### ISSUE TITLE
[Epic#38] 이모지를 채널에 날릴 수 있다!🤭

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#87]
# [Epic#38] 이모지를 채널에 날릴 수 있다!🤭

- 리스너는 화면에 이모지를 날릴 수 있다.
- 이모지를 날리면서 감정을 공유 할 수 있다.
- ManDay: 2

## 완료 조건 ✅

- [x] 이모지를 선택할 수 있는 버튼이 필요하다.
- [x] 이모지를 선택하는 버튼을 Click or Hover하면, 사용가능 한 이모지들이 나열된다.
- [x] 이모지를 클릭하면, 이모지가 슬라이르 쪽으로 랜덤한 방향으로 날라간다.
- [x] 이모지가 날라가기 시작하면, 채널 내 모든 사람들이 날라가는 이모지를 볼 수 있다.
- [x] 이모지가 하나가 아닌 여래가도 정상적으로 잘 날아간다.
- [x] 이모지가 일정 height에 도달하면, 남지 않고 파괴된다.(🤭)

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by happydhKim** [comment]
완성☺️
