### ISSUE TITLE
[Epic#25, Epic#33] 필기 가리기 버튼을 클릭하면, 스피커의 필기 내용이 삭제된다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#88]
# 필기 가리기 버튼을 클릭하면, 스피커의 필기 내용이 삭제된다.

- 리스터와 스피커는 필기 가리기 버튼을 이용해 슬라이드 내 필기를 볼수도 있고, 가릴 수도 있다. 

## 완료 조건 ✅

- [ ] 필기 가리기 버튼 UI 구현
- [ ] 스피커는 필기 가리기 버튼을 클릭하면, 자신의 필기를 보이지 않게 할 수 있다.
- [ ] 리스너는 필기 가리기 버튼을 클릭하면, 스피커의 필기를 보이지 않게 할 수 있다.

## 관련 이슈 📎
- (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다. (#86)

## 레퍼런스 📚
> 레퍼런스 없음
