### ISSUE TITLE
[Epic#1] 사용자는 SNS 계정으로 dropy에 로그인 한다.

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#9]
- 초기 개발환경을 세팅하고, 유저 소셜 로그인 기능을 구현한다.
- 로그인 기능 구현에 필요한 유저 테이블 설계를 한다.

### 설계
- [x] DB User table 설계

### 개발환경 세팅
- [x] 서버사이드 환경 구축 (Express, Apollo server, MongoDB)
- [x] 클라이언트 사이드 환경 구축 (React, Apollo client)
- [x] 유저인증 방식/기술 결정 (Session vs Token)
- [x] Oauth 적용 (Google, Kakao, Naver)

### UI
- [x] 헤더 UI
- [x] 로그인 UI (버튼 3개)

## 레퍼런스 📚
- [제품백로그](https://docs.google.com/spreadsheets/d/1YE7uJFBmL3xCaZYRoaxV8CroAN2vEo2TEbEWLn7zh2g/edit)
- [화면기획서](https://docs.google.com/presentation/d/14fJYKn49Dqipuvr0yJMEFKmG6PMuUL5e1-3ZkHKOMb0/edit#slide=id.g6addb83f12_0_30)
- [구글 OAuth 팝업 지원](https://www.dropbox.com/ko/)
- [네이버, 카카오 OAuth 팝업 지원](https://login.tmon.co.kr/user/loginform?return_url=)
